// <auto-generated />
using DBLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBLib.Migrations
{
    [DbContext(typeof(VsContext))]
    partial class VsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBLib.Entities.VehicleDescription", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasHeatedSeats")
                        .HasColumnType("bit");

                    b.Property<bool>("hasLowMiles")
                        .HasColumnType("bit");

                    b.Property<bool>("hasNavigation")
                        .HasColumnType("bit");

                    b.Property<bool>("hasPowerWindows")
                        .HasColumnType("bit");

                    b.Property<bool>("hasSunroof")
                        .HasColumnType("bit");

                    b.Property<bool>("isFourWheelDrive")
                        .HasColumnType("bit");

                    b.Property<string>("make")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<short>("year")
                        .HasColumnType("smallint");

                    b.HasKey("_id");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
